[app]
github = "https://github.com/OlegDryahlov/"
version = "0.1.3"


[files]
app_about = ["data", "about.txt"]
app_description = ["data", "description.txt"]
app_logo = ["data", "logo.txt"]
target_urls = ["data", "url.json"]

[progress_bar]
fill = "#"
message = "Поиск по имени пользователя"
suffix_base = "(%(index)d / %(max)d) | {site}"
width = 20
