[app]
github = "https://github.com/OlegDryahlov/ShiroGaze"
version = "0.1.4"


[filters]
response_body = true
response_body_not_null = true
keywords = true
keywords_list = [
    "404",
    "not found",
    "not exist"
]


[files]
target_urls = ["data", "url.json"]
text = ["data", "text.toml"]


[progress_bar]
fill = "#"
message = "Поиск по имени пользователя"
suffix_base = "(%(index)d / %(max)d) | {site}"
width = 20
